### ISSUE TITLE
cannot use transmission.get()

### ISSUE THREAD

**Issue by mfaizan1** [grantholle/transmission#8]
I was using node-transmission on which your library is built upon. 

i was able to add torrents with help of node-transmission. and get details of all active torrents aswell. 

but for id or array of ids it wasn't working it was simply returning empty array. 

then i tried your package and it simply crashes on get request 

```

  getTorrentDetails = (req, res) =>  {
        const {params: {id}} = req;
        console.log(id)
        if(!id){
            res.status(400);
            return res.send({success: false, message: 'please provide torrent id'});
        }
        transmission.get(id).then(res => {
            console.log(res);
            for (const torrent of res.torrents) {
                
            }
          }).catch(err => {
            console.log("error: ",err) ;
            res.status(500);
            return res.send({success: false, message: 'something went wrong, please try again'});
          })

}
```
here is the error 
```


TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type undefined
    at checkListener (events.js:73:11)
    at _addListener (events.js:235:3)
    at ClientRequest.addListener (events.js:293:10)
    at module.exports.Transmission.callServer (/Users/faizanulhaq/Documents/personal/torrent/node_modules/transmission/lib/transmission.js:489:9)
    at module.exports.Transmission.get (/Users/faizanulhaq/Documents/personal/torrent/node_modules/transmission/lib/transmission.js:181:10)
    at getTorrentDetails (/Users/faizanulhaq/Documents/personal/torrent/Controllers/transmission.js:47:22)
    at Layer.handle [as handle_request] (/Users/faizanulhaq/Documents/personal/torrent/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/faizanulhaq/Documents/personal/torrent/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/faizanulhaq/Documents/personal/torrent/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/faizanulhaq/Documents/personal/torrent/node_modules/express/lib/router/layer.js:95:5)
```

**Nodejs version : 13**
**Transmissiom daemon : 3**
**transmission-promise : 1.1.4**

**Comment by grantholle** [comment]
Sorry @mfaizan1 this got buried somehow...

Are you still having issues? If you are, could you replicate it in a really simple repo so I can take a look? Like maybe just that function? The stacktrace shows the path `node_modules/transmission`, so it may be referencing the [`transmission`](https://www.npmjs.com/package/transmission) package and not this one, [`transmission-promise`](https://www.npmjs.com/package/transmission-promise).
